import create from "zustand";
import { devtools } from "zustand/middleware";

const store = (set, get) => ({
  loaded: false,
  setLoaded: () => {
    set((state) => ({ loaded: true }));
  },
  soldout: false,
  windows: [
    {
      id: 0,
      title: "Party Round Mag",
      icon: { src: "/img/computer.png" },
      color: "#DF34C9",
      page: "mag",
      selected: true,
      active: false,
      maximized: false,
      minimized: false,
      open: true,
      left: "38vw",
      top: "20px",
      width: "60vw",
      height: "80vh",
      mobileLeft: "22vw",
      mobileTop: "10px",
      mobileWidth: "78vw",
      mobileHeight: "60vh",
    },
    {
      id: 1,
      title: "Buy",
      icon: {
        src: "https://win98icons.alexmeub.com/icons/png/envelope_closed-0.png",
      },
      color: "#160C3F",
      page: "buy",
      selected: false,
      active: true,
      maximized: false,
      minimized: true,
      open: true,
      left: "130px",
      top: "150px",
      width: "500px",
      height: "490px",
      mobileLeft: "2vw",
      mobileTop: "15vh",
      mobileWidth: "96vw",
      mobileHeight: "460px",
    },
    {
      id: 2,
      title: "VOL.001",
      icon: { src: "https://win98icons.alexmeub.com/icons/png/msagent-3.png" },
      color: "#222222",
      page: "vol",
      selected: false,
      active: false,
      maximized: false,
      minimized: false,
      open: false,
      left: "300px",
      top: "330px",
      width: "400px",
      height: "400px",
      mobileLeft: "4vw",
      mobileTop: "20vh",
      mobileWidth: "92vw",
      mobileHeight: "50vh",
    },
    {
      id: 3,
      title: "Unreleased Drops",
      icon: { src: "https://win98icons.alexmeub.com/icons/png/msagent-3.png" },
      color: "#222222",
      page: "drops",
      selected: false,
      active: false,
      maximized: false,
      minimized: false,
      shortcut: false,
      open: false,
      left: "calc(100vw - 550px)",
      top: "calc(100vh - 470px)",
      width: "500px",
      height: "400px",
    },
    {
      id: 4,
      title: "Party Round",
      icon: { src: "/img/pr.png" },
      color: "#000000",
      page: "iframe",
      selected: false,
      active: false,
      maximized: false,
      minimized: false,
      open: false,
      left: "calc(100vw - 880px)",
      top: "calc(100vh - 680px)",
      width: "800px",
      height: "620px",
      mobileLeft: "2vw",
      mobileTop: "7vh",
      mobileWidth: "96vw",
      mobileHeight: "70vh",
      src: "https://www.partyround.com/",
    },
    {
      id: 5,
      title: "Terminal",
      icon: {
        src: "https://win98icons.alexmeub.com/icons/png/console_prompt-0.png",
      },
      color: "#222222",
      page: "terminal",
      selected: false,
      active: false,
      maximized: false,
      minimized: false,
      open: false,
      left: "50px",
      top: "calc(100vh - 550px)",
      width: "520px",
      height: "300px",
      mobileLeft: "0",
      mobileTop: "1vh",
      mobileWidth: "100vw",
      mobileHeight: "50vh",
      shortcut: false,
    },
    {
      id: 6,
      title: "Party Round Mag",
      icon: { src: "/img/computer.png" },
      color: "#DF34C9",
      page: "logo",
      selected: false,
      active: false,
      maximized: false,
      minimized: false,
      open: true,
      left: "calc(100vw - 480px)",
      top: "calc(100vh - 300px)",
      width: "400px",
      height: "230px",
      mobileLeft: "20px",
      mobileTop: "55vh",
      mobileWidth: "86vw",
      mobileHeight: "100px",
      shortcut: false,
      taskbar: false,
    },
    {
      id: 7,
      title: "Ads for Party Round",
      icon: { src: "/img/pr.png" },
      color: "#000000",
      page: "iframe",
      selected: false,
      active: false,
      maximized: false,
      minimized: false,
      open: false,
      left: "calc(100vw - 880px)",
      top: "calc(100vh - 680px)",
      width: "800px",
      height: "620px",
      mobileLeft: "2vw",
      mobileTop: "30vh",
      mobileWidth: "96vw",
      mobileHeight: "50vh",
      shortcut: false,
      taskbar: true,
      experiment: true,
      href: "https://opensea.io/collection/partyroundads",
    },
    {
      id: 8,
      title: "New York Tech Week",
      icon: { src: "/img/pr.png" },
      color: "#000000",
      page: "iframe",
      selected: false,
      active: false,
      maximized: false,
      minimized: false,
      open: false,
      left: "calc(100vw - 880px)",
      top: "calc(100vh - 680px)",
      width: "800px",
      height: "620px",
      mobileLeft: "2vw",
      mobileTop: "7vh",
      mobileWidth: "96vw",
      mobileHeight: "70vh",
      shortcut: false,
      taskbar: true,
      experiment: true,
      src: "https://nyctechweek.xyz/",
    },
    {
      id: 9,
      title: "Party Pong",
      icon: { src: "https://win98icons.alexmeub.com/icons/png/joystick_alt-0.png" },
      color: "#000000",
      page: "pong",
      selected: false,
      active: false,
      maximized: false,
      minimized: false,
      open: false,
      left: "20vw",
      top: "calc(100vh - 580px)",
      width: "600px",
      height: "420px",
      mobileLeft: "2vw",
      mobileTop: "7vh",
      mobileWidth: "96vw",
      mobileHeight: "40vh",
      shortcut: false,
      taskbar: true,
      experiment: true,
    },
    {
      id: 10,
      title: "Startup Supreme",
      icon: { src: "/img/pr.png" },
      color: "#000000",
      page: "iframe",
      selected: false,
      active: false,
      maximized: false,
      minimized: false,
      open: false,
      left: "calc(100vw - 880px)",
      top: "calc(100vh - 680px)",
      width: "800px",
      height: "620px",
      mobileLeft: "2vw",
      mobileTop: "7vh",
      mobileWidth: "96vw",
      mobileHeight: "70vh",
      shortcut: false,
      taskbar: true,
      drop: true,
      src: "https://www.startupsupreme.xyz/lookbook",
    },
    {
      id: 11,
      title: "VC Puzzle",
      icon: { src: "/img/pr.png" },
      color: "#000000",
      page: "iframe",
      selected: false,
      active: false,
      maximized: false,
      minimized: false,
      open: false,
      left: "calc(100vw - 880px)",
      top: "calc(100vh - 680px)",
      width: "800px",
      height: "620px",
      mobileLeft: "2vw",
      mobileTop: "7vh",
      mobileWidth: "96vw",
      mobileHeight: "70vh",
      shortcut: false,
      taskbar: true,
      drop: true,
      src: "https://vcpuzzle.com/",
    },
    {
      id: 12,
      title: "Poached Eggs",
      icon: { src: "/img/pr.png" },
      color: "#000000",
      page: "iframe",
      selected: false,
      active: false,
      maximized: false,
      minimized: false,
      open: false,
      left: "calc(100vw - 880px)",
      top: "calc(100vh - 680px)",
      width: "800px",
      height: "620px",
      mobileLeft: "2vw",
      mobileTop: "7vh",
      mobileWidth: "96vw",
      mobileHeight: "70vh",
      shortcut: false,
      taskbar: true,
      drop: true,
      src: "https://poached.xyz/",
    },
    {
      id: 13,
      title: "Party Grounds",
      icon: { src: "/img/pr.png" },
      color: "#000000",
      page: "iframe",
      selected: false,
      active: false,
      maximized: false,
      minimized: false,
      open: false,
      left: "calc(100vw - 880px)",
      top: "calc(100vh - 680px)",
      width: "800px",
      height: "620px",
      mobileLeft: "2vw",
      mobileTop: "7vh",
      mobileWidth: "96vw",
      mobileHeight: "70vh",
      shortcut: false,
      taskbar: true,
      drop: true,
      src: "https://partygrounds.com/",
    },
    {
      id: 14,
      title: "BIGTECH Fellowship",
      icon: { src: "/img/pr.png" },
      color: "#000000",
      page: "iframe",
      selected: false,
      active: false,
      maximized: false,
      minimized: false,
      open: false,
      left: "calc(100vw - 880px)",
      top: "calc(100vh - 680px)",
      width: "800px",
      height: "620px",
      mobileLeft: "2vw",
      mobileTop: "7vh",
      mobileWidth: "96vw",
      mobileHeight: "70vh",
      shortcut: false,
      taskbar: true,
      drop: true,
      src: "https://bigtechfellowship.com/",
    },
    {
      id: 15,
      title: "Burn The Runway",
      icon: { src: "/img/pr.png" },
      color: "#000000",
      page: "iframe",
      selected: false,
      active: false,
      maximized: false,
      minimized: false,
      open: false,
      left: "calc(100vw - 880px)",
      top: "calc(100vh - 680px)",
      width: "800px",
      height: "620px",
      mobileLeft: "2vw",
      mobileTop: "7vh",
      mobileWidth: "96vw",
      mobileHeight: "70vh",
      shortcut: false,
      taskbar: true,
      drop: true,
      src: "https://burntherunway.com/",
    },
    {
      id: 16,
      title: "Helpful VCs",
      icon: { src: "/img/pr.png" },
      color: "#000000",
      page: "iframe",
      selected: false,
      active: false,
      maximized: false,
      minimized: false,
      open: false,
      left: "calc(100vw - 880px)",
      top: "calc(100vh - 680px)",
      width: "800px",
      height: "620px",
      mobileLeft: "2vw",
      mobileTop: "7vh",
      mobileWidth: "96vw",
      mobileHeight: "70vh",
      shortcut: false,
      taskbar: true,
      drop: true,
      src: "https://helpfulvcs.com/",
    },
    {
      id: 17,
      title: "Startup Ipsum",
      icon: { src: "/img/pr.png" },
      color: "#000000",
      page: "iframe",
      selected: false,
      active: false,
      maximized: false,
      minimized: false,
      open: false,
      left: "calc(100vw - 880px)",
      top: "calc(100vh - 680px)",
      width: "800px",
      height: "620px",
      mobileLeft: "2vw",
      mobileTop: "7vh",
      mobileWidth: "96vw",
      mobileHeight: "70vh",
      shortcut: false,
      taskbar: true,
      drop: true,
      src: "https://startipsum.com/",
    },
    {
      id: 18,
      title: "Recycle",
      icon: {
        src: "https://win98icons.alexmeub.com/icons/png/recycle_bin_full-4.png",
      },
      color: "#0000a8",
      page: "recycle",
      selected: false,
      active: false,
      maximized: false,
      minimized: false,
      open: false,
      left: "calc(50vw - 250px)",
      top: "calc(50vh - 200px)",
      width: "500px",
      height: "200px",
      mobileLeft: "0",
      mobileTop: "0",
      mobileWidth: "100vw",
      mobileHeight: "210px",
    },
    {
      id: 19,
      title: "Go Tron",
      icon: { src: "https://win98icons.alexmeub.com/icons/png/joystick_alt-0.png" },
      color: "#d53c3d",
      page: "tron",
      selected: false,
      active: false,
      maximized: false,
      minimized: false,
      open: false,
      left: "calc(100vw - 880px)",
      top: "calc(100vh - 680px)",
      width: "800px",
      height: "620px",
      mobileLeft: "2vw",
      mobileTop: "30vh",
      mobileWidth: "96vw",
      mobileHeight: "40vh",
      shortcut: false,
      taskbar: true,
      deleted: true,
      location: "C:/",
      date: "09/06/2022",
      type: "Experiment",
    },
    {
      id: 20,
      title: "Cube",
      icon: {
        src: "https://win98icons.alexmeub.com/icons/png/charmap_w2k-0.png",
      },
      color: "#000000",
      page: "iframe",
      selected: false,
      active: false,
      maximized: false,
      minimized: false,
      open: false,
      left: "calc(100vw - 880px)",
      top: "calc(100vh - 680px)",
      width: "800px",
      height: "620px",
      mobileLeft: "2vw",
      mobileTop: "30vh",
      mobileWidth: "96vw",
      mobileHeight: "50vh",
      shortcut: false,
      taskbar: true,
      deleted: true,
      location: "C:/DESKTOP",
      date: "07/19/2022",
      type: "Experiment",
      src: "https://party-round-cube-hpqgm40cn-tjcages.vercel.app/",
    },
    {
      id: 21,
      title: "Fluid",
      icon: { src: "/img/pr.png" },
      color: "#000000",
      page: "iframe",
      selected: false,
      active: false,
      maximized: false,
      minimized: false,
      open: false,
      left: "calc(100vw - 880px)",
      top: "calc(100vh - 680px)",
      width: "800px",
      height: "620px",
      mobileLeft: "2vw",
      mobileTop: "30vh",
      mobileWidth: "96vw",
      mobileHeight: "50vh",
      shortcut: false,
      taskbar: true,
      deleted: true,
      location: "C:/DESKTOP",
      date: "05/27/2022",
      type: "Experiment",
      src: "https://www.partyroundfluid.xyz/",
    },
    {
      id: 22,
      title: "Party Animals",
      icon: { src: "https://win98icons.alexmeub.com/icons/png/tree-0.png" },
      color: "#000000",
      page: "image",
      selected: false,
      active: false,
      maximized: false,
      minimized: false,
      open: false,
      left: "calc(100vw - 880px)",
      top: "calc(100vh - 680px)",
      width: "500px",
      height: "530px",
      mobileLeft: "15vw",
      mobileTop: "30vh",
      mobileWidth: "70vw",
      mobileHeight: "70vw",
      shortcut: false,
      taskbar: true,
      deleted: true,
      location: "C:/",
      date: "05/20/2022",
      type: "NFT",
      src: "https://uploads-ssl.webflow.com/6290ef4dfec30d2f6dbbf4e4/631a6da6d43e4dc058f5a1ca_ezgif.com-gif-maker%20(24).gif",
    },
    {
      id: 23,
      title: "Cap Table Pokémon",
      icon: { src: "https://win98icons.alexmeub.com/icons/png/joystick_alt-0.png" },
      color: "#000000",
      page: "image",
      selected: false,
      active: false,
      maximized: false,
      minimized: false,
      open: false,
      left: "20vw",
      top: "calc(100vh - 580px)",
      width: "600px",
      height: "420px",
      mobileLeft: "2vw",
      mobileTop: "7vh",
      mobileWidth: "96vw",
      mobileHeight: "40vh",
      shortcut: false,
      taskbar: true,
      experiment: true,
      src: "https://pbs.twimg.com/media/FPwQxMgVEAAbFCc?format=jpg&name=4096x4096",
    },
    {
      id: 24,
      title: "Paint by @jsngr",
      icon: { src: "https://win98icons.alexmeub.com/icons/png/joystick_alt-0.png" },
      color: "#000000",
      page: "iframe",
      selected: false,
      active: false,
      maximized: false,
      minimized: false,
      open: false,
      left: "10vw",
      top: "calc(100vh - 900px)",
      width: "800px",
      height: "620px",
      mobileLeft: "2vw",
      mobileTop: "7vh",
      mobileWidth: "96vw",
      mobileHeight: "40vh",
      shortcut: false,
      taskbar: true,
      experiment: true,
      src: "https://paint.diagram.com/",
    },
  ],
  setWindowDimensions: (id, { top, left, width, height }) => {
    let newWindows = get().windows;
    newWindows[id].top = top;
    newWindows[id].left = left;
    newWindows[id].width = width;
    newWindows[id].height = height;
    newWindows[id].mobileTop = top;
    newWindows[id].mobileLeft = left;
    newWindows[id].mobileWidth = width;
    newWindows[id].mobileHeight = height;
    set((state) => ({ windows: newWindows }));
  },
  toggleActiveWindow: (id) => {
    let newWindows = get().windows;
    newWindows.forEach((window) => (window.active = false));
    newWindows[id].active = true;
    newWindows[id].minimized = false;

    set((state) => ({ windows: newWindows }));
  },
  openWindow: (id) => {
    let newWindows = get().windows;

    if (!newWindows[id].open) {
      newWindows[id].open = true;
    }
    newWindows[id].minimized = false;

    set((state) => ({ windows: newWindows }));
    get().unselectAll(id);
  },
  closeWindow: (id) => {
    let newWindows = get().windows;
    newWindows[id].open = false;
    newWindows[id].minimized = false;
    newWindows[id].maximized = false;
    get().unselectAll();
    set((state) => ({ windows: newWindows }));
  },
  hideWindow: (id) => {
    let newWindows = get().windows;
    newWindows[id].minimized = true;
    get().unselectAll();
    set((state) => ({ windows: newWindows }));
  },
  maximizeWindow: (id) => {
    let newWindows = get().windows;
    newWindows[id].maximized = true;
    set((state) => ({ windows: newWindows }));
  },
  unmaximizeWindow: (id) => {
    let newWindows = get().windows;
    newWindows[id].maximized = false;
    set((state) => ({ windows: newWindows }));
  },
  toggleSelectedShortcut: (id) => {
    let newWindows = get().windows;
    newWindows.forEach((shortcut) => (shortcut.selected = false));
    newWindows[id].selected = !newWindows[id].selected;
    set((state) => ({ windows: newWindows }));
  },
  unselectAll: (but = -1) => {
    let newShortcuts = get().windows;
    newShortcuts.forEach((shortcut) => (shortcut.selected = false));
    set((state) => ({ windows: newShortcuts }));
    let newWindows = get().windows;
    if (but > -1) {
      newWindows.forEach((window) => (window.active = window.id == but));
    } else {
      newWindows.forEach((window) => (window.active = false));
    }
    set((state) => ({ windows: newWindows }));
  },
});

// allows the use of the redux devtools extension with zustand
const useStore = create(devtools(store));

export default useStore;
